### ISSUE TITLE
按自己的需求加了一个随机数生成

### ISSUE THREAD

**Issue by stephenLYZ** [zxc0328/chrome_extension_onekey#1]
```
    var rand = Math.round(Math.random()*5);
```

**Comment by misakar** [comment]
![2015-12-24 5 56 23](https://cloud.githubusercontent.com/assets/10671733/11993030/ac0981c0-aa67-11e5-8dbe-61bf94225d94.png)

**Comment by stephenLYZ** [comment]
hhhh

**Comment by misakar** [comment]
![canvas](https://cloud.githubusercontent.com/assets/10671733/11993087/4e66b302-aa68-11e5-82ab-3f1c6476fcdf.png)
